(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"muñeco animacion_atlas_1", frames: [[988,0,331,703],[0,0,527,755],[0,757,489,749],[529,0,457,741],[982,743,457,728],[491,757,489,738]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_6 = function() {
	this.initialize(ss["muñeco animacion_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_5 = function() {
	this.initialize(ss["muñeco animacion_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_4 = function() {
	this.initialize(ss["muñeco animacion_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_3 = function() {
	this.initialize(ss["muñeco animacion_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_2 = function() {
	this.initialize(ss["muñeco animacion_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(ss["muñeco animacion_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.Símbolo1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("ACcIiQgVgBgNgNQgHgPADgTQADgQAKgQIAGgKIAAgCIAEgCIAGgIIAAgeIAQgMQgChEgOhDIh9ABQiUABhdAfQgeAKhAAdQhNAjgjASQg/AfguAeQgwAfgUAJQgpASghgIQgJgWATgcQAJgNAWgTIABgbIAygpIASgaQARgXAogoQAbgbASgOQATgPAlgWIBwhEQhPguhCguIhHgyQgqgegfgSIgagQQgOgJgJgKQgLgMgDgPQgEgQAGgNIFBBQQA3AOAeAEQAjAEA6gBICkgCQArAAAagFQASgDAkgKIAEgBIAEgHIABgEQADgNAJgZIACgGIACgOQADgigMhFIgdikQgHgIgDgHQgLgUADgcQACgTAJgfIAVABIAAgJQAUgLAYALQAXAJAOAWQAJAOALAcQANAgAGAMQAGAMAkAuQAKAOAIAMIAwA3QAgAkAhAiQBOBSB/BlQAYATAIAMQAPAXgKAUIgGACIgBALQgWANgVAOQgFANgIALQgNASgWATIgoAfQiWBwiODDQgPAVgJAJQgOAQgPAJQgQAJgSAAIgDAAgAoHhaIAAgCIgDgBIADADg");
	this.shape.setTransform(68.0184,54.6668);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,136.1,109.3);


(lib.orejainfo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.text = new cjs.Text("oreja", "28px 'Montserrat'", "#333333");
	this.text.lineHeight = 41;
	this.text.lineWidth = 135;
	this.text.parent = this;
	this.text.setTransform(116.05,-88);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ADKAAQAACOg7BkQg7BkhUAAQhSAAg7hkQg8hkAAiOQAAiNA8hkQAyhVBEgMQAGgCAFAAQAHgBAFAAQBUAAA7BkQA7BkAACNg");
	this.shape.setTransform(20.15,34.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiNDyQg8hlAAiNQAAiMA8hlQAxhUBFgNIALgCIAMgBQBUABA6BjQA8BlAACMQAACNg8BlQg6BjhUABQhSgBg7hjg");
	this.shape_1.setTransform(20.15,34.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.text}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-90,254.1,159.3);


(lib.ojos = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAEHaIhKgBQgfAAgSgEQgqgKgagmQgbgmAEgrQAHgEAIACQAIABAFAFQAGAFAMATQAXAjAoARQAoASApgGQApgGAigbQAigaARgmIAyACQAJAXgcAkQgaAggRAQQgaAXgbAFQgKADgQAAIgLgBgAlhEoQgpgDglgRQgPgIAAgIQgRgJgPgjQgHgQAAgGQABgRgBgIIgIgVQgDgJAAgNIACgWQABgVgGgLIgGgMIAAgIQABgFgBgDIgIgKQgDgEAAgNQACgwAOgsQAEgMABgJQABgGgBgPQAAgOABgIIAIgYQAEgOgDgJIAKgFQgCgNATgSIAsgrQA3gDAaAHQAWAQAbAKQAdAKAGAFQAUANgBASIATAQIAGAMIAIAMQAMAVAEAfQACATAAAkQAABGgGAoQgDAYgGAXIgMA2QgEARgEAPQgGARgHANQgQAhgcAWQghALgjAAIgOgBgAmDitQgKAFgGALQgIANgGAeQgWB+gDBHQgCBEATAlQANAZAXAPQAYAPAagDQAZgDAVgWQASgTALgdQAHgRAHgjQAIgkAGgRQgVgBgVgGQgGADgKAAQghgBgcgMIAAguQgGgMgCgSIgBggIgBhzIgGAAQgIAAgIAFgADlEYQgTgCgJgGQgFgDgMgSQgJgPgLgBIAAgPQgHgBgGgMQgHgOgFgDQgFgEAAgNIAAixQAAgYAFgKQAHgQgCgiQgCgjAGgPIAFgOQACgIgBgGQgCgNAIgZIAPgqIAJgGQgCgDACgEQABgFAFgCIAIgEQAEgCACgEQBJgHBFAWQACAJAHADQAOAFAIAMIAfAsQAKAOABAJIAAATQAAAMAEAGQAHAIgBATIAAAyQABAagHAKQgFAIABAPQABATgCAGIgEALIgFAKQAAAEAAAJQABAIgCAFIgHAOQgFAIADAFQAEAKgJAUQgIAUADAKIgKAFQgIAjgHARQgLAbgRAQQgGAGgBAEQgeAGgeAAQgUAAgUgDgADnjXQgXAjgLBDQgMBEgFBzQgEA4ANAbQAHASAZAdQAWAbATACQATACARgTQAMgOAJgZQAdhMARhQQgsACgsgOIADgOIgQgFQgPgkAJhGQAMhPgHgegAIJktQAFgTgagWQghgcgsgOQgrgOgsAEIg/AIQglAFgZgGQgEgSACgRQARABAYgIIApgNQAYgFAlABQBMACA0ATQBEAaAgA2IABA4IgMABQgaAAgWgNgApEkrIgBgrIAfgVQAmgYAQgNQAbgXALgHQAQgIAfgGQBsgVBJAfIAAAyQgPAEgXgHIgngLQgQgCgYAEIgnAGQgcADgHADQgKAEgTASQgbAZgfAOIgVALQgMAHgEAJgAiHmUQgDgcANgYIgUgIQABgEAAgGIBoAAIgmAtQgLABgLgBQgIANgCAPgACsm5IAAghIA7AAIAAAXIgUAFIAAAHg");
	this.shape.setTransform(58.15,47.4625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AACHmQgsgBgagDQgngFgdgMQgjgOgXgaQgZgdgEgiQANADANALIAXAUQAlAhAvARQAvARAwgDQAxgCAtgVQAugWAggkQANgOAHgFQAMgJAMACQAJAWgQAYQgKAQgZASQgqAfgdALQghALg/AAIgKAAgAj3G3IAbACIgDAAIgGABQgIAAgKgDgAkMGgIAAAAIAAANQgBgGABgHgAEIEyQABgCgDgDQgDgCgEAAQgWgEgSgQIgGgGQgegRgLgPQgPgUgFgnQgHg2gDgJIgQgsIAAgCIgBgCIgDgKIAGgCQgFgeALg2IARhcQADgQADgJIAIgIIAPgQIAMgRQAGgLAHgFQAHgFAMgDIAVgDIAXgHIAAgDIAFABIAhgMIACgBIALAFIARAIIACABQAWAGATARQAKAJAQAWQATAZAHAOQAKAUAGAaQAPBBgGBRQgEAzgSBhQgEAYgJAKQgHAHgKABIgDAAIgRALIAAAAQgIAMgHAFQgFAEgGACIAAgCQgGgCgHgBIgLAEQgaAGAAANgAElipIgYAAQgKAHgLAUIgLARQgQAdADAQIgUAFQgBAEgDADQgCADgEAAIAAAPIgLAFQAEAagGAYIgGAWIgBAHQACAXAEAYQALBEAiBYQAMABAtAQQAPAFANACIAGgBQAMgDAVgCQANgHAMgQQAKgOANgcQAPgfAAgSQABgHgCgMIgCgSQAAgJADgaQAEgegEglQgDgXgIgqQgGghgIgTQgLgbgUgNQgVgOgoAAIgCAAgAk7ESQgLgBgXACQgXABgMgCQgFAAgRgGIgrgQQgWgIgHgIQgEgFgEgIIgCgJIgDgBIgDgGIgIgKQgBgPAAgWIAAgEIgMAAIgBjGQAAgnAKgRQACgFAIgLQAHgJACgGIACgOIADgOIABgFQAHAEAJgCQAEgQADgGQAFgMAIgGIASgLQALgGABgIIAegFIAAgCQAPACAPADIACABIAjABQgCAEAIACQAWADAZAMQANAGAeARQASAMgEAJIAKAFQAHAZAXAPQAAAHADAJIAEAQQAEANAAAbIAABPQAAAggDAPIgLAuIgHAaIgQAoQgFAOAAALQgGACgHACQADgKAFgKQgFgCgGADQgGACgEAFQgFAHgGAPQgIAQgdAPIgqAWgAnRApIgFADIgDAyQAAAKAEACQAJAGgDAWIAKAFQgBAFADADQANAQgFAVIAHAAQAHASAJAIQAIAHARAFQAqAMAogIQArgIAZgeQAWgbALg2QAIgugCgyQgBgggHgYQgBgMgEgNIgJgbQgFgQgBgLIgBgMQgBgHgDgEQgFgJgRgGQhCgYhEgEQADAEgBAGQgBAFgEAEIgCACIgPgBQACAFgFAGIAAAAQgVANgKAXQgGANgBAMIgHABQgJBGAHBEgAD4COQgQgQgFggQgEgVAAgpQAAgTADgHQAEgJARgSQAQgQADgMIAXgBQAMgNAhAJQgBADAAAEIABAAQAAADADADQADADAEAAIAAAEIAFAEIAFADIAAACQANAOAKAWQAJAWABATQAAApglAjIgOAMIgEAEIgBAAIgMAGIAAACIgBgBQgMAFgMABIgGAAQgYAAgQgPgAl2CRQgIgJgOAAQADgEgCgFIAAgBIAAgBIgEgGQgKgJgDgFQgDgHAAgNQgCggAFgRIAGgSIAAgDIACgPIgCgFIADgBQADgOAJgKQALgNAhgMQAMgEAIABQAIACAOALQAFADAPADQANACAGAFQAMAJAAAbQACBRghAkQgLAMgNAEIgKABQgIAIgHACQgFACgIAAQgLAAgQgFgAkMgFIADgCQgGgLgLgHIgDgCIgIAAQASASAHAEgAKWjyQAAgcgNgaIgCgDQgNACgPgJQgLgGgVgTQgegcgqgWQg7gehDgLQg9gKg7AHQgZARgLAaIgagDQgJgVAegfQATgUAMgJQATgOATgEQAOgDAbAEQCSAUB9BOQAfAUAOAPQAVAVALAcQAKAdgCAegAq1knIAAghQA8gQB6g5QB1g2BDgQQA9gOAmANQAZAJARAUQARAVAAAYQgSAHgUgSQgRgWgMgIQgGgEgGgCQAAAGgDAFQhEACggAKQgRAFgbANQhAAfgYAPQgnAXgMAGQgeANgYgEIgBgFIggAPQgVALgOAEQgLACgKAAQgIAAgIgCg");
	this.shape_1.setTransform(57.941,42.5894);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgdH7QhhgHhZhDQgSgQgIgXQgIgXAEgYIAUACIAAAXQAYAKALAYQAgAeAqARQApASAtACQArACAqgOQArgOAjgbQgGgZAUgWQAUgWAaAEQAFAQgYAdQgXAdAGARQgkAigzAQQgmAMgoAAIgVgBgAFkEkIAAgFIgUgFIAAgFQgDgBgDgCQgGgBgTAAQgJAAgHgCQgTgBgSgDQgIgKgLgBIghgXQgOgCgIgNQgJgMACgOIgKgFQADgHgEgJIgIgQQgCgGABgNQABgOgBgGIgHgTQgDgJAAgUIAAhlQAAgTADgJIAHgRQADgKgDgGIAKgFQACgTAJgQIAJgFIABgPQAVgSATgVQAegTAlgIQgBgHADgIQAoAFAlARQAFAHAKAIIAQAOQAIAJALAYIASAuQAGAXgEAXIALAFQADALgEATQgFAYAAAGQAAAJACAIIADAfQACARgDAHIgGAKQgEAHABAMIACAUQAAAOgKATIAEAFQAKAMAIAFQANAIALgGIAAgFIAZADIAAAMIgKAFIAAAFQgdAAgPgDIgMgEQgJgEgEgGIgEgFQgBAGACAEIgKAFIAAAPIgKAFIgBANIAIAFQALAGAOABIAAAXQgYgCgVgMIAAgEIgDgBIgTAUIAMgCIAAgFIAPADQADAPgGAGQgCADgFACQgKAGgHAAQgFAAgDgCgAEEDTIAEAKQACADAEACIAIAEQAFACAEAGIABABIAJAAQABgFgDgGIgHgOIgCgJIgDAAQgQgBgRgFQAIAGACAGgAE1DMIAAADQABAKACAEQACAEAKAIIAEgCQAJgEAJgIIAAgCIgKgFIAAgFIgKgFIAAgBIgRADgADiDUQAIAGAJAFQgFgJgMgCIAAgWQgPgHgPgKQAMAXASAQgAFsDBIgNADIAAABIAKAFIAAABIAIgMIgFACgAD7imQgfAXgVAkQgUAigIAoQgKAwAIA4IACABQAEAKgBAMIAKAFQgEAPAWATQAVARAKAGQASALAQADQARADAggFIAAgTQALgDAKAHQAFADADAFIAVgHQAUgIALgOIgBgDIACAAIAGgVQAFgXABgpQAEhOgKgqQgQhFgwgeQgPgKgPgBIgIgBQgYAAgbAVgAmyDjQgFgDABgCIgTgFQgCgGgLgFQgEgCgDgEIgBgBIgHAAQgKAAgIgFQgPgLgCgVIAWAAIAAgeIgIgEIgEAEQgIAHAAAFQgMAIgNgDIAAgUQALgDAIgLIAFgHQADgEADAAIAAgEIAFgDIAAhQQAAgRADgIQAGgNACgHQABgFgCgOQgBgNACgGIAGgLQAEgGABgEIgCgMQgBgIACgEQAHgFABgEQACgDgBgFIAAgIQABgDAHgKQAFgKgDgFIAKgFIAAgPIAKgFIAAgPQANgIAIgMIAigCQADAAACgCQAAgBAAAAQABgBAAAAQAAAAAAgBQgBAAAAgBICHALIALAPQAWAFARAPQASAOAJAUQADAGACAJQABAHgBANQgEA7ADAwIgLAFQABAigFAPIgFAPIgBAIIgBAHQgCAFgFAIQgFAHADAFIgJAFQgKAigIARQgNAagTAOQACAFgEAGQgEAFgGADIgMAGQgGAEgBAFQgLAJgaABIgaAAQgyAAgcgMgAmCC9IgFAOIgDAEQARAEAUgCIAGgBQAFgEAEgFQAGgHACgJIgVABQgOAAgMgCIgFAHgAkpCxIgWAEIABAKIAAAHQAQgHAOgNIgBgEIgIADgAmvCeQgEAKgNAJQAIAIAKAGIALAHIAGgEIAAgFIAKgFIAAgKQgLgFgQgNIgBACgAnhBfQAEAnAPAZIAAABIAEgEIAIgHIADgGQgKgJgFgHQgJgMgJgWIgBACgAlrCQIgCAIQARAAASgFIAAAAIAGgJQADgFgCgEIANgCIAAgFIAUACIgDAGQAmgYARgoIAJAAQALgdAIgeQAQg+gJgpQgGgggUgaQgUgbgdgPIh8AAQgdAggSAxQgNAlgKA5QgFAagDAXIALABQgBALACALIAKABIAAAMIgEACQAGAOAMAJQAFAOAYASQAYAQAHAMIAEgHgAK2j4IABgDQACgFAHgEIgBADIgEAEIgCAFgAKTkwIgKgFIAAgPQgNgHgIgNIgTgGIgLgOIgTgGQgOgQgXgEIgOgOIgTgGQgHgJgMAAQgHgKgNAAIgMgPQgNABgHgLQgQABgOgLQgxgDgsABQgRABgGACQgKAFgGAIIgUAGIgFAeIgZgDIAAgHIgMgIIAAgWIARgFQgBgIAGgHQAFgGAIAAQAHgFAJgFQAfgQA3AEIAsAFQAaADARAAQANALARgCQAHAMANgBIALAOIATAGQAHAKANAAQAHAKANgBQAGAMAMgCQgCAFALAEQAOAEAKAMIATAGIALAOQAVAHASATIAAAIIgHACQACAEgEAGIgGAJQgCAFAAAHIAAANIgCALgAq/liIABgPQAVgRAogFIBDgJQAkgJA2gkQA8goAcgLQAxgSA2ALQA3ALAmAlQAIAIAAAHQgCAHgJAEQgVAIgcgRQgbgWgQgHQgngRgxAXQgQAHgXAPIgmAYQg2Aig/AQQgyAMgyAAIgagBg");
	this.shape_2.setTransform(58.4375,45.2824);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},6).to({state:[{t:this.shape_2}]},10).to({state:[]},3).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.9,-6,140.8,102.1);


(lib.ojoinfografia = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.text = new cjs.Text("ojo", "28px 'Montserrat'", "#333333");
	this.text.lineHeight = 41;
	this.text.lineWidth = 151;
	this.text.parent = this;
	this.text.setTransform(192,-121);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ADXAAQAAB9g/BXQg/BYhZAAQhYAAg/hYQg/hXAAh9QAAh8A/hYQA/hXBYAAQBZAAA/BXQA/BYAAB8g");
	this.shape.setTransform(21.5,30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiXDUQg/hXAAh9QAAh7A/hZQA/hXBYAAQBZAAA/BXQA/BZAAB7QAAB9g/BXQg/BYhZAAQhYAAg/hYg");
	this.shape_1.setTransform(21.5,30);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.text}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-123,346,184);


(lib.narizinfo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.text = new cjs.Text("nariz", "28px 'Montserrat'", "#333333");
	this.text.lineHeight = 41;
	this.text.lineWidth = 171;
	this.text.parent = this;
	this.text.setTransform(210,-151);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ADNAAQAAAwg8AhQg8AihVAAQhUAAg8giQg8ghAAgwQAAgvA8giQA8ghBUAAQBVAAA8AhQA8AiAAAvg");
	this.shape.setTransform(20.5,11.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiQBRQg8giAAgvQAAgvA8giQA8ghBUAAQBVAAA8AhQA8AiAAAvQAAAvg8AiQg8AihVAAQhUAAg8gig");
	this.shape_1.setTransform(20.5,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.text}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-153,384,177);


(lib.muñeco = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("Ah9byQgigEgUgJIgTgKQgcgRgVgWQgDgnAEgkQgqgQgTgjQgHgOgHgYQgOgtgEgXQgIgqAChXQACg9AIh7IAFhRQAHhfAAgyQAAhRgLhAIgIgtQgDgaAEgTIADgNQgigOgXgXQgbgcgPguQgJgdgJg5IgtkdQgJg7gCgaQgFgwABgmQACgoAKg4QAOhAAFggQAMhCANiJQAMiHANhEQAUhpAqg4QAvg/BUgdQAegKAggEQgPgOgOgTQgOgTgWgkIgGgKQgmgIgngbQg0gjgRguQgGgPgCgRIgFAAQgLgBgFgEQgFgEgCgOQgHg7gDg8QgJgIgIgRQgOgdgPgBIAAgXIAVgGQgHgIAGgLQAGgLALgDQAJgCAMAEIAPAGIgDgKIgDgKIgEgEQgpgiAJgfIAJgFQgPgWAGgXQAeADAZAPIADgFQgVhGgKhIQALgEALAFQAMAFAEAKIAOgCIAAgjQAmALAjACIANAjQAIgPAFghQADgOAIgJQAJgLALgBIAAgPIAegFIAAgXQAUgCAWANQAOAIAVAUIAXgQIABhAQAFgRAQgIQARgJAQAGIAAAJQASAHAQANQAWARAMAXQAPgfAVgcIACgMQAIgMASACQARADAJANQAHAJAHASIAGARIAYABQABgdANgcQAHgOAMgHQAOgJAKAJQAGAMADASQAKgFAMAEQgCAvgKAuQAEAKAGAHQAJACAGADIAKgmIARgDQAIgYgDgYQAeAGAYASIAAAcIAVACQgDATABAJQADARANAEQAHADAQgDQAPgDAHAEQADAhgHAUIgNAeQgGASAEAMIAJgOIAKgOQAGgGAIgCQAKgBAFAGQASAHANALIAAAWIgCABIAAAHIgKAFQADAggLAcQAFADACAGQACAGgCAFQgBADgFAGIgHAPQACAKAAAKQAKgOALgKIgEAHQgMAUgDAJQgDAJgCATIgCAKIgFgBIgBANQAAAKgDAGIgMATQgHALACAIIgBAAQAMAxgBA1QgBBGgVA/QgMAkgQAaQgKATgRAWQgtA9gqAgQgNALgPAJQAcAJAXAQQAiAXATAgQAMAVAHAfQAFATAFAlQAXCtAJBYQAPCRACB1QACB5gKCYQgHBcgSC2QgGBCgKAjQgQA2ghAeQgaAYgpANQgUAGggAGIABA8QABAoAFAUIAKAmQAIAcAAA8IAADSQABBBgGAlQgFAhgRA0QgPAvgIAhQARgDAVgBQBHgDBDAJQBFAIATAkQAHAPABAVIgCAmIAAAhQgCASgHAMQgLATgZAJQgRAGgeACIg8AEQABAPgCAKIgGAbIgBANIgCANQgCAJgIAJQgUAbgigBQgNAAABAGQhgAOgkADIgRACQgaACgeAAQg5AAhAgLgAieaDQALAEAPAJIAYAOQAUAKAcAEQARADAhABQAGgEAPAAQAjAABGgNIA1gKQAQgDAFgEQAFgCAHgJQAHgIAGgDIgDgNQhKADhhABIABglQgZABgZgBQgeAfgkAJQgUAFgiABIgeAAgAkCQRQgBBQgGBYQgEAvgFAuQgHA3ACAYQACAcAPA1QAKAjAIASQANAdATAQQAaAUAlAAQAjgBAbgUQAcgUATgoQAWgwAIhBQAEgoAAhPIgBloQAAhTgEgpIgGgzIgBgQQheAFhfgDQgkgBgcgEQAOC8gBCMgADcXOIg+AUIgFABQgDAOgEALIBIADQASAPAWAFIAGAIQAzgIAygTQAAgUgegQQglgTgnAAQgTAAgUAFgABDLGQAGAYgBAgQgBAbgGA1QgDAcgBA4IgEG3QgBA3gCAdQgDAcgFAYIAGgGQASgSAJghQAEgNAIguQAKhAAWg+IATg2QAJgiADgrQACgagBg0QAAg6gDglIgHgvIgHgvQgLhRAIhRIhEAHgAipr0Qg1AIguAoQgqAlgZA2QgWAtgMA+QgIAmgIBKIgqFoQgLBeABAvQABAoAOBZIAdC2QAKBAALAjQASA0AhAeQAjAhA7AKQAqAJBBgDQB2gFBzgSQAogGAYgIQAjgKAXgSQAsghAThCQANgsAFhQIASkZQAJh+gDhHQgDgqgKhUIghkOQgGgwgGgYQgKgngRgbQgWgjgmgUQgmgUgqABIgdAAQgQgBgIgJQgFgFgCgGQgXAAgYgCIAAADIgGAAIgBAHQgCAJABACIgZgCQgDgGAAgKQgWgBgegDQgjgEgYAAQgRAAgNACgAjHv6IgJAEIASAdQAXAlAGAUQAJAGAKAKIASATQAVAVAiAQQAXAKApANQAXAIAPABQAYACAegJQBUgaBDhGQA+hCAjhZQATgygEggQgCgQgOghIgLgcIgGgaIgIgBQgOgCgKADIgKgYQgPAAgNgIQgEgIABgXIAAgHQghgKgUgEQgpgJghABQgrABhKAXQgbAJgOAGQgVAJgOALIAIABIAAAeQgKgDgJAHQgJAIABAKIgJAAIgBAOQABALAHAqQAFAhgEAUIgIADIABAkQATAtACAzQgJADgKgDQgJgEgIgHQgFgGgHgKIgMgQQgOgQgGgIQgKgPAEgMIgLgFQgMAkgIAlgAmt0EIAAgBIgBAAIABABgAgD6JIABACIABACIABgFgAglEnIhFgBQgSAAgJgEQgMgGgIgRIgMgeIgMgaIgMgaQgGgNgFgSQgEgPgDgVQgMhSAFhRIAHhJIAPiPIARiOQAHg3AMgbQAUgsAmgNQAUgHArADQBEAEA9gFQASgBAIAFQAGAFAFAOQAJAdACAXIAIAFIACB4QABBEgFA1IgHBCIgsEqQgLBFgSAjQgOAdgUALQgOAJgUADIgaABIgLAAgAgsnUQgTAHgUAhQgXAlgDAUIgBAfQgBANgHAZQgEAUABAbIABAjQABAUgDAOIgEATQgDALgBAIIAAASQAAALgBAHIgEAMIgEANQgDAMACAYQgBAIgFARQgFAQgBAJQgBAQAIAbQAMAiABAJIADAZQACAIADAIQAEANAJAGIAfBKQAPADAQgGQAQgFALgMQATgTAMglQAFgRAIgiIAKgtQAHgiABgPQABgVACgKIAHgXQACgIgBgMIAAgUQAAgRAGgeQAGgeACgRQALhBgFhCQgCggADgNQAFgOABgHQAAgJgEgRQgDgQgGgKQgJgOgVgIQgNgFgYgEIgVgBQgOAAgHADgAIB1tIgBgJIACADIACAGIgBAAIgCAAg");
	this.shape.setTransform(51.6452,149.5375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AkEbwQAAgFgJgBIgWgCQgNgBgJgDQgRgEgRgNQgKgIgTgSIgrgsQgJADgJgFIgEgDIgYgBQgHgWgBgXQgHgOgEgQQgFgZAFgYIAIggQAFgSgEgNIAJgGQASg/ArgvQALgtAbgjQAGgmAMgmIAMgmQAHgVACgRIAEgeQABgUACgLIAMgsQAIgaABgRQAAgQgFgWIgLgkQgHgdgCgeIgKgFQgIgDgKgBQgSgagNgcQgYgygJg1IgBgHQgbgNgUgUQgbgbgPgvQgJgdgJg4IgokGIgYACIgGhFIACAAIAPgRIgDgZQgFgvACgmQABgoALg4QANhAAGghIAIg1IgEAMIgJAXIAAgMQAAgLADgOIAFgaQAEgUgBgbIgBgvQgBgYABgSIAHgNQAGgKAKgFQALhnALg5QAUhpAqg5QAvg/BUgcQAegKAggFQgPgOgOgSQgOgTgWglIgZgqIgEgDQgQAMgXgNQgLgGgRgXIgog3QgWghgTgoQgRgjgBgaIAAgWQgBgNgCgIQgFgOgQgMQgKgIgUgJIAAgeIAPgHIAAgXIBDADQgDgJgJgJIgQgPQgIgJgEgKQgEgMAFgJIAJgFQgQgoAHgqQARgDASAFQARAGANALQgUgsgHgZQgMgoADghQAcgEAUATQAEgLgCgOQA0AAAuAYQAEgJgCgXQgCgVAGgJQALgQAjAAIAAgNQAkADAigLQgDgVANgOQATgBASAHIAGgIIAAgPIAHgCIABgIIAWABIAAgLIAZACIAAAIQARAAAUASQAdAYAGADQAMgTAAgVIABgLQABgGAEgDQAEgFAJABIAPACIALAOIAcAFQAIAcAPAXQALgXACgZQAAgNAEgGQAGgFANABQASACAEgBQAIAKANgBIAAB6IAMgMIAAgWQAUgEAKAFQAAgPADgHIAGgKQACgFgBgLQgBgLABgFQALACAUAAIgBgMQAEABANAAQAKAAAFAEQAFADADAJQAJAEAGAIQAEAFADAKIAEAQQADANALAWIASAkIAEAIQAUgCAVAFIAAANIAeAFQADAIgDALIgHASQgGAUACATQAJgKANgEQAOgEAMAFQADAMgGAPQgEAJgKAPIAAAEQAAAMADAGQADAEAGAEIALAHQALALgFAfIgnACQAHAIABAIQABAHgCAHQgDAGgGADQgDABgHABIgLABQgEACgCADIgBAHIgDALIAAAAIAAAAQgHAVgTAJIgPAeIADAKQAMAygBA0QgBBHgVA/QgNAjgPAbQgLASgRAWQgtA9gpAhQgOAKgOAJQAbAKAYAPQAiAXASAgQANAWAHAfQAEATAFAlIAEAdIAEACQAFADACAFQACAGgCAFIAMAFIABALQBEA5ApBSIANAcQA0B0AqBwIAIAGIAAAPIAKAFQACBIgFAfQgGAhgSAIQgHAagNAGQgGADgQAAIhdgCQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAIgIAAQgFgBgEgGIgGgJQgEgDgIgCIgFgCIAICVIgGACIgPABIgBAKQgGBbgSC3QgHBBgKAjQgQA3ghAeQgIAIgLAHIAvAwQBABBAiAeQA5AxA0AeQgHA2ANA2IAKAnIADAUIADATQADAMAMAeQAWA4AaBsQAKAqABARIACAaIADAZQACALAHAbQAGAYACAOQACAYgGAfQgEASgMAjQgOAGgPAEQAQANANANIABAyQgBAcgJASQgIASgSAOQgSAOgTAHQgWAJgdADQgSABgiAAIhZgBIgwgBQgbgBgVgEQgOgCgGgHIgHgLQgFgHgEgCIgMgDQgHgCABgGQgMgBgLgDIglgBIgLgiIgBAEIgFASQgHAVgLALQgMALgXAHQgaAGgMAFQgVAIgLADIgSACIh7AKIgrABIgmgBgAlcZUIANALQAUATATAOQAcAUAQAGQAYAJAvAAQAmABASgDQAdgEAxgRIAogOQAQgFACgJQADgLgPgNIgOgMIgegBIAAgNQgSAdgVAcIg/gBQgMgjAUgqQgTABgaAGQgcAGgKAFIgVANQgMAHgKACQgGACgOAAIgaAAIgBAAIAAAAIgFAAIgfABgAEHYBQgNAEgVAPQgWAQgMAFQgSAGgDAHQgCAGAEAOQAEANgDAGQAHAHAQADIAbAFQAKAEAQAPQAQAPAJAFQANAGAeAAQA6gCAfgGQAxgKAegZQABgIgNgIIgqgbQgFgCgEgEIAAgBIgjgWIgbgCQACgGAAgHQgXgNgRgGQgUgHgRAAQgOAAgMAEgAmfYNQgCAEABAEQAEgDAFAAQgCgEACgGgAkeXoQgHAOAAAKIgIAGIgGAOIAFgDIAQgLQAJgGAVgJQAcgKANgCQAGgBAUAAIBbABIAQgXIAGgJIAIACQAiAHAiABQAVgqAQgLQgCgKADgKIgCgJIgFASQgDgKgFgLIgLgUQgGgMgCgJQgCgJAAgNIAAgVQgBgVgIgWIABgDQgLgVgPgbIg4hiIgegyQgSgcgSgTQgRgRgbgWIAAAFIAAABIgDgDQgfgggOgSQABBzgTBwQgGAqgKAaIgMAjIgFAeQgDATgDALQgDAJgHAMIgLATQgPAbgHAbQglAmgRAyQAygBAzgMIATgGIgGAKgAA1YPIAHAEIgDgMIgEAIgAnsDdIAdC3QAKBAAMAiQALAgAQAYIAAARQABApANAaQAFALANAQIAUAbIAHALIAIAJQAFAEAHACQANAbATAbQAvBEBhBNIAzAoQAbAYASAWQALAPANAWIAWAmIAqBFIARABIAIAMIATATIgCAvIAFAMQAOAiALA0IAKABQADAoAAAVIAAALQAMBNAKAsIABgCIABgGQAEgBADgDQADgCAAgEIAUgGQAegeAsgEQAKgBAVABIAmACQgCASAFAJQAIAMAbAEQAbAEANAAQAXABARgFIAYgLQAOgGAKgBIAEAKQAUgFANgLIALgUQgIgKgBgSIgBgfQAAgUgJgnQgch5gZg+QgOgkgCgLIgEgmQgCgKgHgWQgHgUgBgMIABgnQAAgXgHgOQgHgMgUgOIg6gqQgegWgPgOQgMgMgSgYIgdgkIghghIgOgPQgSACgRAHIAIgnIABgFIgTAEIAAAfIgGAAIgHgLIgpgCQALgyAHgyIATgFQAigLAYgRQArghAUhDQAMgsAGhPIAGhfIACAAQANhdAEh3QADhFAAiOQAAhYgHgrQgDgWgIgKQgEgGgGgEIgXi4QgGgvgGgYQgJgogSgbQgWgigmgUQgmgUgpABIgdAAQgQgCgIgJQgEgEgCgHQgYABgXgCIgBACIgGABIgBAHQgCAJAAACIgZgDQgCgGAAgJQgWgBgfgEQg6gGgeAEQg2AJgtAoQgqAkgaA2QgVAugNA9QgHAmgJBLIgVC6IAmg9QAUgfANgOQAPgRAegYIBCg2QA8gxAggXQA1gnAvgWQAggQAYgCQAjgCASAVQANA6gDA3QgBAagGAlQgJBJgHAyQgFAfgGAZIgJAcQgPAwgdA2QgUAkglA7QgXAlgQARQgbAdg3AcQiJBIhvgRIAEAegAhKnaQgbAMgeAVQgRAMglAdIh+BnQgZAUgLAMQgUATgJAUIgIARQgFAKgEAHIgJAKIgJALQgFAGgEALIgIARIgOAWIgOAVQgKAUgHAjQgQBMAFAsIAKAFQgDAGADAHQADAGAGABIAAAPIAygEIAvgXQA3gaAegSQAfgRAPgQQAKgKAOgUIAXgfQAjg3Acg1QAPgeAIgUQALgbANgxQAJgkACgKIAKhKQAEgegDg3IgGAAQgBAEgJAFgAFyhWQAGAGAIANQAFAFAZALQATAJADAMQAOAEALgWQAFgLADgEQAGgIAHgCQgCgJAEgLIgJgFQAAgLgMgZIgchDIghhRIgmhZQgQgmgQgRIgLgMQgGgHABgHIgCgDIAKBgQALBqAEBcIAAASIACAyIACAAQATAAAIAHgAkHwbQgHANgJALIATAfQAYAlAFAVQAJAFALALIARASQAWAVAiAQQAWAKApANQAZAIAOACQAZACAdgKQBUgZBDhHQA+hBAjhaQATgygFggQgCgQgNggIgLgcIgMgrQgHgVgLgLIgFgBIAAAZQgXAEgTgMQgDgIABgXIAAgBIgGgCIhDgcQhnAchwASIAAgJIgPAHIgDAVQgBAggDALQgDAJgGAMIgMAUQgSAigHAnQgDAUAGAKQAFAJANAFIAXAJQAVAJAKAWQALAWgFAWQgHgBgGAEQgGAEgBAGQgiADgkgqQgVgZgGgGQgRgRgRgGQABAbgNAYgAEB5TIAAAFIAGAHIACABQgDgKgEgKIgBAHgAF+V0IAHgCIABAFIgHACIgBgFgAAFNaIgFgFIAFgBIAAAGgAAzMRIAGAGIgGABIAAgHgACCLmIABgEIAEgOQACAKgGAKIgBgCgAitJ4IASgBIAAADQAAAPgCAHQgJgJgHgPgApBiPIADAAIgGALIADgLg");
	this.shape_1.setTransform(58.5722,150.585);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AmUcTQh2gQiMhSIhJgsQgUgMgIgHQgQgMgGgOQgGgMgDgSQgJg2AFg5QAEgrAPgRQAjgLAhAAIAdgpQAcgqAZg7QAOgiAYhLIAhhjIALgFIAdhaQgLgggKghQgLgMgMgUIhEhzQgGgCgGgJIgHgQIgHgPQgGgIgCgGIgEgTIgTgpIgMgLQgbgcgPguQgJgdgJg5IgNhRIgJgTQgLgaAGgbIADAAIgRhtIgXACIgHhFIADAAIAPgRIgDgYQgEgoAAghIg4gBQgdgBgQgCQgYgFgQgLQgfgWgHgyQgDgRgBgZIAAgqIgBgoQABgWAGgQQAJgXAfgdQAbgZAhgXQAigXBEggIAMgGIAAgIIAGgNQAHgKAKgEQALhoALg5QAThpAqg4QAwg/BTgdQAfgKAggEQgPgOgOgTQgPgTgVgkQgYgngNgaQgNgFgLgJQgWgRgfgtIg+hZQgVgfAAgTIABgSQgBgKgDgGQgEgGgLgDQgNgDgGgCQgQgGgHgRQgIgQAGgQIAngPIgegWIAAgeQAlgCAlAIQgSgSgKgaQgJgaADgaIAigPQgHgvAEgzIAWgFIAAgeIAwgHQgCgWAEgRIB6ASIAAggIAbgGQgFgIAAgKQAAgKAFgIQAFgIAJgEQAKgEAJACQAGABAMAGQAMAFAGABQAPACAYgRQgEgfARgaQAcgDAZAQQgDAlANAjQAFgHgBgIQAFACAFgEQAFgDACgFIAEgKIADgKQALgPAhAGQgBgUATgNQATgNASAIIAEBJIAIAAQAJgMgDgOQAHABAHgGQAGgGgBgJIArADQAEAeAQAbIAZgCQAEgHgCgJQAJACAJgFIARgLQAYgOAaAJIAAArQAIgVgEgZIAkADQgFAnAOAkIATAGQATAfADAhIAlAAQAEATgBAXQAGAAAGAFQAGAGgBAHIAMAFIAAAOQAPADANAOQAKAJAMASQALAQAAALIAAAPQABAEACADQADADADAAIAAAeQgOgBgSAMQgaARgFACQgPAEgGAEQgNAHgMAbIgwAFQAMAhAEAUQAMAxAAA1QgBBGgWA/QgMAkgQAaQgKATgRAWQgsA9gqAgQgNALgPAJQAcAJAYAQQAhAXASAgQAMAVAHAfQAFATAFAlIAEAdIAcAHIA6ASQBBATAgARQANAHAYAQIC6B5QApAbARAPQAPANAeAlQAPASAIAKQAJARADAQQAMAJAFAUQADAMAAAXQABAjgDASQgEAcgOATQgVAbgpAIQgXAFgxgBQhCgCgYgDQg/gGg6gXQgygThcg0IgPgIIADAyIAPABQABA+ANA8IgHgIQgDgCgIgDIgGgCIAICVIgGABIgOACIgBAJIgGBNIAAAPQAFBAATA3QAbBQA4BAQAXAQAgAkQAlAqAPANQAOANAZASIApAeQBBA1AkBQQAfBKgCBMICeFxQAhBMAJAqIAIAkQAEAVAEAOIACAFQAtAAAnAFQBOAJA+AbQAeANAKASQAEALAAAYIAABEQAAAegIANQgKAVgbAJQgUAHggACQhRAEg1ABIgCAGQiJAWiKgaQgvgJgMgXQgOgPAAgeQACgjgBgRIgBgVQABgKAFgGIgDgEQgngtgRgWQgegngUghQgXgngmhVQgkhUgYgoQghg3gpgmQgVgUgdgWIg2gmQg0gmgvglQgDAIgBALIgJA9QgLBHAAApQAAAmgRAHQgFADgLgCQgHAagBAoQgCA8gFAXQgJAlghA4IgKASIADAAQAIAMgFAUIgLAhIgDASIgEAQQgGAQgRAMIgHAEIAJAHQAcAXAJAMQAJAMAFAMQAJAYAAAnIAABBQgfAJg+ABIgbAAQhGAAgmgEgAlUbQQA4AGAigPQglgngXgVIgBgFIgBgbQgCgPADgLQgrgQgwABQgQABgHgDQgHgCgHgHIgMgKIgBgBQgJgMgegMIgKgEIgGgHQgLgOgJgFQgJgFgRAAIgcgBIgBADIg2gSQgCAHgEADIgNAKQgJAHACAHQgMANgPADIAAAHQgQADgKALQALANAcASQBcA3BCAeQgGgJgBgMIAAgDIAFAEQAhAcAWAHQAOAEACAGIA3ABIgCAHQgSABgSgCQAvAOAtAGgAHeaSIAKAFIABAOQAbAUApAHIABgkQAtgDBjAQQBeAQAzgHQA/gJAbgpQgSgcgdgOQgOgHgngKQgxgLgcgFQAJAfgHAWQgHgBgZACQgVABgLgGQgLgGgIgRQgTAQgRATQgSAVgMAGQgLAGgPACIgcABQgsgBgVgIIgEgCIgMAHgAnYavIAAgCIgFAAIAFACgAi8MXQAKABAJAHQAHAFAHAJIADACQATADAEADQAHADAEAGQAFAGgBAHQgBAEgCAEIARANICFBhQAwAjAfATIAiAUQATAMAMALQAVARAgAsQAeApANAWQAWAjAcBEQAgBLAQAdQAaAxAsA2QAZAfA5BAQAPAQALgBQAKAAANgNIAjgkQAbgbAUgLQgWhNgohcQhHiZgihNQgmhXghheIATAAQAGgwgZg6QgOgfgog/QgOgWgNgEIgNgCIAAgZQgagFgegMQgQgXgSgVQgbgggVgIIgTgGQgMgDgGgFQgEgEgHgLQgGgLgFgEIgEgDIgMgRQgNgSgIgOIgCALIgBgKQgCgVgOggQgSgogDgNQgFgSgFgGQgHgwAAgVQAAgLAFgjIAAgHQgCgpAJggQAJh4ACh2IgOgBIAAh0QABhYgIgrQgDgVgHgLQgEgFgGgFIgWi3QgGgwgGgYQgKgngRgbQgWgjgmgUQgmgUgpABIgeAAQgPgBgJgJQgEgFgDgGQgXAAgXgCIgBADIgGAAIgBAHQgDAJABACIgZgCQgCgGAAgKQgWgBgfgDQg6gHgfAFQg1AIguAoQgpAlgaA2QgWAtgMA+QgHAlgIBHIAOgHQA9gdApgPIA0gRQAegKATgLQAdgqAlgkQANgNALgFQAIgCASAAIBbAAQAbAAALAGQASAJAIAWQAGAQADAbQAEAjABAOQABAcgDAVQgDAYgJAYQgWBLgoAoQgPAQgpAcIh+BVQhcA/g2AaIg8AdIglAVQgSALgNAFQgDAhADAXIAKAFQgDAGADAGQADAGAGACIAAAPIABAAQAAAfgBALIgCAVIAAAJQgPAAgPgDIAFAfIAbCsIAcBZQAZAXAaAmIAfAuQARAUAZATIAuAhIBZA7QAtAeAaAJQAKADAXAGQAWAFAMAEQAQAGAqAaIAIAFIAAAAQAGgDAHAAIAHABgApXWdIAGADQA1AUAdAFIAAAGIBjApQAUAJAAALQAMAHAWAGIAcAIIAIgXIATg3IADgIQgBAMACANIA0ACQATgrAGgWIAKghIAIgQIAJgQQAGgOAIgaQALgnACgRIACgdIACgeIAPg+QAIglgHgZIgJgFQABgQABgJQAGgTABgKIACgUIAAgUQABgLAEgUIAEgUQgnghgPgYIgIgOIgSgDQgTgFgfgRQgigUgPgFQgOgFgegHQgdgHgPgGQgTgHglgYIhphGIgjgZIABACQAKARAMAMIANANQAIAIADAGIAHANIgBADIADABIAGAMQAGAOAHAHIABgDQAFgCAEgBIABACQAKALAMAJQgIAkAeAqIAPAXQAGAOgDALIAIgBIgBA1QABASAEAKIgVgBIgBAJQgFAmgWA/Ig4CkQgLAhgJAWQgKAYgRAhIgSAiIANAAQAEALgGAOgAtBkFQglAZghAhQgjAkADAdQAAAJAGARQAVA2AhAKQARAFAagFIAUgFIAGgfQANhAAFggIAJg2IgFANIgIAWIAAgMQAAgKADgPIAFgZQACgOABgQQgfAQgVAOgAqvkBQgIBDAMApIAEAQIgLASIAAABIAogUQAjgQAQgJQAggSAogeIBOg2QBAguAYgVQATgQAPgPQA6hAAFhWIgKgFQgCgRgIgKQgFgFgGgDQgIgCgHACQAFAZgKAJQgDADgIACIgLADQgNADgPANIgbAVQgOAKgjANQheAmhUAnIhRAnIgLBXIAcgrIgEAegABal9QAGA/AFA5QAVACARAGQAUAHAnAVIAuAZQA3AfAcAMQAwAVApAGQAdAFAZgFQAugIAbgmQgNgTgGgYQgGgEgGgIIgKgOQgkg6hSg2IhFgrQgsgagZgTIglgbQgTgNgcgLQgNgGglgOIgcgKQACAYAIAzIgIgIQgFgIABgHIgDgCIALBfgAoCwoIgDAJIAXAmQAYAlAFAUQAJAGAKAKIASATQAWAVAhAQQAXAKApANQAYAIAPABQAYACAfgJQBTgaBDhGQA/hCAhhZQAUgygFggQgCgQgOghIgKgcIgMgrQgIgYgOgLIAAAbQgXAEgTgLQgDgIAAgXQABgJgBgHIgFgBIgjgNQgVgJgQgCQgjgDguAaIglAWQgWAMgRAGQgjAMgmgGQACANgNAJQgJAGgJgBIgPBwQgEAdACASQACAZAQANQAGAFANAGIASALQAMAKAEAPQAEAQgGAOQgQAGgSgDQgSgDgOgKQgMgJgRgaQgSgYgNgJQgcABgRAugAkm2oIAFgDIgCgFIgDAIgAi14AIADAAIgDgIIAAAIgAtzaaIACAHIgCAAIAAgHgADyNRIACABIAAADIgCgEgAi3L8IAHAGIgHABIAAgHgAmWJmIARAAQAAAOgCAHQgIgJgHgMgAsrikIADgBIgHALIAEgKgABmlEQgCgVAAgkIAAgiIACALQAMBOgEAzQgGgXgCgag");
	this.shape_2.setTransform(82,152.7397);

	this.instance = new lib.CachedBmp_1();
	this.instance.setTransform(-33.4,-29.85,0.5,0.5);

	this.instance_1 = new lib.CachedBmp_2();
	this.instance_1.setTransform(-33.15,-27.05,0.5,0.5);

	this.instance_2 = new lib.CachedBmp_3();
	this.instance_2.setTransform(-33.15,-29.45,0.5,0.5);

	this.instance_3 = new lib.CachedBmp_4();
	this.instance_3.setTransform(-49.2,-31.05,0.5,0.5);

	this.instance_4 = new lib.CachedBmp_5();
	this.instance_4.setTransform(-60.2,-32.65,0.5,0.5);

	this.instance_5 = new lib.CachedBmp_6();
	this.instance_5.setTransform(-41.45,-9.3,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.instance}]},2).to({state:[{t:this.instance_1}]},2).to({state:[{t:this.instance_2}]},2).to({state:[{t:this.instance_3}]},2).to({state:[{t:this.instance_4}]},2).to({state:[{t:this.instance_5}]},2).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.2,-32.6,271.3,377.5);


(lib.flechafinal = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAPGWQgkgGgNAEQgIhdAChdQhggBgvADQhPAFg8ATIgrAQIgsAPQhVAchBgPQgMhFAdhCQAHgPATggQARgeAHgRQAehFgUhIQgGgVgOgfIgXgzQgZg/AOguIAXgIIAAgPIC5AAIAiAeQBFA7AsAaQBFAnA+gCQgEh5ARh5IBfADQAHAKAMAFQANAEALgDQAGBGBOBKQCTCQDnBHIABBnQgcABgfAOQgTAJgiAVIkMCqQgnAZgRANQgeAYgQAZIgJANQgGAIgFAEQgKAHgSAAIgTgCg");
	this.shape.setTransform(56.3867,40.8056);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,112.8,81.6);


(lib.boca = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AkRAyIgBgGIgegUIgWgQQgLgJgFgKQgGgNAAgeQAAgKADgEQAFgFAMACQAPADAFgBQANAdAMALQAMANAeANQBAAbAvALQAxAKBAgCQAkgBBNgJQAmgFAPgFQAWgIApgbIAegXIAVgWQANgOAKgGIAAgPQAJgBABgJIA1ADQAEAugVAMQgBANgUASIgnAgQglAggVALQgVALgdAFQgSADgiADIhyALQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQAAAAAAABQiKgIh/gtgAggAFQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAIgBADgABtg0IACgDIAYgCQgOAFgKADg");
	this.shape.setTransform(34.9389,10.275);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AhhCuIgwgBQgagCgVgDQgqgIg6gYQgjgOgUgNQgdgSgPgXIgNgXQgJgNgJgFIAAgPIgKgFQgEgYALgZQAHgPAKgIIAEgGQANgPAdgPQA4gbAmgKQAkgKBBgFQBKgGAcgFIAZgFIAagEQARgCAWABIBEABQBsACA5ANQBdAVAxA4IACAOIAUAPIAAALIAAABQAGAEADAMQAJAmgUApQgTAmgkAZQgfAVgsAMQgiAJgxAGQhDAHhVACIgxAAIhngBgAAwBVQgmABgPACQgeAEgWAKQgLAEgTAMIgLAHIAmAAQBkgCBmgKIAJgBIgHgFQgXgOgTgFQgOgDgcAAIgMAAgAlYgqIgYANQgEAFgBAFQgCALANARQAlAtA0AaQATAKAbAJQAYAJAUAFIACgJQAHgRAPgLQAMgKATgGQAJgEAagGIAggIQg9gBg/gDQgDgEgLgBQgngGgVgNQgagUgQgGQgHgYgBgMIgBgJQgVAIgNAHgAFSgbQgIACgBAJQgZAAgPASQgdACgVASIhBAFQgGAAABAEIg2AEQAcAEAPAGQALAFARAKIAcARIAYALIAKAFQA4gQAiggQAdgaACgaQgGgCgEgDQgEgDgCgGIgFgKIgFgIIgFAMgAAFhzQglADhTAKIg5AHQgeAEgQADQgPADgcAKIAGABQABALgGAIQAOAQAZAKQAPAHAXAFIAmAIQAJACgDAEQASgIAagBQAJAAAkACQAsABBHgEQAtgDATgDQAjgEAbgIIBBgYQAUgJARgNQhCgkhlgFIglgBQgnAAgtAEg");
	this.shape_1.setTransform(36.1209,7.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AiyCQQg4gJgdgLQgdgLgrgYIhagxIAAgHIgKgCIgBAAQggAJgbACIAAgrQALgJATgIIAggMQANgGAngXQAagOAegOQA4gbAbgLQAvgSAngIQAdgFAmgCQAXgBAuABQBDABAjADQAwAEBOAPQBCALAkAOQATAHApAWIB+BCIAAAyIgCAAIgEAHQgFAFgQAJIhDAfQhEAfgdAJQglAMg5AIQhdANhdAAQhmAAhlgQgAhwBkQBnAOCQgPQA8gGApgKQArgKAigQQgiADg2ABQhwABiLgEIj7gLIgXgCQBaApBiAOgAj5AAIAQABQCuAFBOAAQCNABBvgHQApgCAUgGIAYgIQhBgnhrgZQiLghhvAIQg2AEgpAMQgcAJg6AbIglARIAJABQASACAHgBQAFAXgEALg");
	this.shape_2.setTransform(39.675,3.4936);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AhVDQIACgBIACADIgEgCgAjICzIgYgBQgOgBgJgFQgGgDgJgGIgOgLQgKgHgLgDIgDgCIAAgCIgEgCQgXgNgagZIgqgvQgbgcgIgLIgEgGQgIADgJABQgUACgMgLQgGgFgBgJQgBgKAGgGQAYAAAMgFQgBgIAGgDIAHgBIACgDQAAAAAAgBQABAAgBAAQAAgBAAAAQAAAAAAgBIAGABIAIgKQAMgNAhgWIApgaQAugdAZgMQAogVAkgJQAagGAdAAQASAAAKADQAJADATAMQARALALACQAZAFAZgVIAOgMQAIgGAHgDQAJgEARAAQAlgBAdAOQAOAHAPAOIAbAYQApAkA6AkQAlAWBHAlIgFAuQgSAAgVgKQgKgEgOgIQgIANgOAIQgXAKgJAIQgFAFgKAOQg1BMhZAcQgWAHgkAFQhSANhTgHIAAAFIgBAGQgngOgrgCgAibiXQgnADg3AjQhEArgXAJIgZAIQgNAFgIAHQgGAFgGAKIgEAGIAGAJQAIALAWAQQALALASAZQAWAYAoAVIACAAIABACIAJAEQBSAmBYADQAbABAVgCQB9gFBEgxQAXgRASgVQAKgHAQgXQAPgVAMgGIAVgJQAHgEAEgEIgugfQhEguhBg7QgXgKgeATIgYAQQgOAJgJAEQggAMgmgQQgXgJgngdQACALgUABgAhmBhQhDgNgigoQgRgvAFgxIAKgFQgEgMAHgMQAGgLAMgGQAQgHAhADIDhARQAiADANAKIgCAEIAfAGIgWgDIgJgBQgCAHAFALQAHAVABAFQAAAHgGAPIgQAmQgRAUgMALQgRAQgSAGQgOAGggACIg5ACIgHAAQgdAAgXgEgAiKg4QgQAHgLAMIAAApQAeAgAoAJQAYAGAtgCQAmgCASgJIAkghQASgPgDgNQgSgBgKgQIiagPIgEgCQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBABAAIgIgBQgNAAgMAFgAHrAyIAAAEIgBABIABgFgAk+AAIAAgbIAHgGIgBAGQgDALAAARIgDgBgADMgHQABgLgBgJQgDgTgNgJQgEgDgFgBIArALIgBAuIgRgFgAjihRQgSAJgLADIgCABQAPgIAQgFg");
	this.shape_3.setTransform(46.4429,6.2718);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AAAEAQgzgBgigJQgzgPgjglQgSgUADgPIgKgFQADgGgDgIIgGgNQgEgIgFgQIgJgcIgEgQQgDgNABgbIgKgFIgBiaQAAgYACgMQAGgVAOgQQArgTAtgCQATgCAmACIAsACIAqgXICVADIAyAUIAAAOIAJAGQAGAOADANQACAJABAbIACB7QABAagFAOIgEALQgCAGgBAEIABAMQABAIgCAEQgBAFgFAIQgGALADAXIgKAFQAFAQgVAXQgbAegQANQgVARgoAWQggASgVAEQgKACgOAAIgLAAgAici2QgFAJgKAAQACAJgEAMIgIAVQgCAGgBAKIgBARQgBAMgFAWQgCAUACAOIAKAFIAAAsIAKAFQgDAHAEAMIAIAUIABAHIACAHIAHAIQACADgBAGIAAAIQABAEAFAGQAEAFAEAMQAIASAVASQAfAaAnAJQAmAKAWgPQAIgJAMABQAAgFAIgEQAtgUASgTIAUgaQAKgMAUgPQgDgHADgIIAHgQQAGgQgEgSIALgFQgDgKADgOIAHgZQADgPABgdIABhMIgKgFIAAgPIgKgFIAAgPQgMABgJgKIgZgFIgEgCQAAgBAAAAQgBgBAAAAQAAgBABAAQAAgBAAAAIhGAAIAAAIQgNgBgHAKIgTAHIgSANQgXADgWgIIgcgLQgLgDgMAAQgaAAggANgAACBwIgWABQgeACgOgOQgIgIgFgUQgEgOgBgRIgDglIgFgYIgFgYQgDgiAPgcIAJgFIAAgQQAbgIAjgBQAVgBApADQAOABAGAEQAKAHADAUQANBSgfBJIgLAdIgdAfQgKgDgNABgAgOhVIgUAFQABAEgDAGIgFAKQgEAHABALIACATIgCATQgBAKADAHIAIAOIABAKIABAKQACAHAGAEQAGAEAHgBQAHAAAEgFQAGgFAAgHIAJgFQgCgGAHgMQAIgLgDgGIAKgEQgDgHADgJIAGgPQAHgRgDgUIgxgUIAAgFIgKAAg");
	this.shape_4.setTransform(43.2833,11.5893);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("Ah/D1QgWgLgXgQQgTgNgJgNIgNgWQgIgMgJgDIAAgQIgJgFIgVhWQgShVAJhYIgkgFQgEgbAKgKIAHgGIAIgFQAJgHANgWQAMgVALgHQANgIAdAAQAqgBAaAEQAgAEAbAKQAiANAJABQAbAEAngQIBCgcQAdgHAtACQBCAEAIgBQASAMAIAUQAJAUgEAUIANAFQgEAKADAPIAHAZQAEAPAAAfIgBCWIgKAFQACAkgGAQQgGAOgUAUQgZAagQAOQgYAUgXAKQgQAIgdAGQhCAPhCAAQhAAAhAgOgAgaDJQAFACgCAEICLgYQARgNAXgGIBZhaQACgIgBgRQgBgQADgIIAFgMQAEgIAAgRIAAgrQAAgNgEgHIgGgLQgCgEABgIIACgMIgFgVQgIgYAEgYQgSgMgNgSIgtgBQgEAAgDACQgEACACADQgLADgcALIgxAUQgQAHgNAEQglALgogKQgPgIgPABQAAgIgPAAQgPABAAgJIgogFIAAgIQgQACgNgLQgLAAgNAPQgPARgIADQAEAGgEAJIgGAQQgEAJAAAQIAAA0QAAAWAEAKIAHARQABAEgBAJQgBAJABAFIAGALQAEAGAAAFIAAAIQgBAFACADIAEAFIAEAFQABADAAAFIAAAIQAAADAIAMQAFAIgDAFIATAQQAOAlAnAVQAiARAsgBQAGAAADACgAgXCnQggAAgTgFQgYgHgSgTQgbgcgEgyQgCghAJg3IAGgjQADgTAIgHQAFgGAMgCIAUgDQAIgCAKgHIASgLQAZgPApAAQAXAAAwACQAuAAANACQAhAFAOAUQALAQAAAoIAABtQAAAcgFANQgMAhgvARQgjANguAEQgZACgoAAIgRAAgAAMA7QgWAIgGANQgMARAAAUQAdAHAogKQAdgIA4gXQAQgFAGgHIAAAAQgIgDgFgFIgHgFQgDgEgEAAQgNgDADgEQg/AAgkAMgAAUhSQgFACgGAAQgQABgPAIQgPAIgJAOIgCAOIgKAFIAAAXIglAHQgFApARAlIAFAHIACg6QAKgBABgJQAQAAAWgFIAkgKQBMgSBKAZQACgcgEgeQgUgagPgHQgRgJgfABQgrABgHgBQACAFgGADg");
	this.shape_5.setTransform(38.6657,12.5376);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AhdDdQg4gIgggVQgIgFgKgJQgOgNgIgCIAAgjIgKgFQADgHgEgKIgHgSIgDgTIgHgXQgLghgCgcIABgmQABgYgCgOIgGgWQgJglAHgnQAYACAWgMIAMgHQAHgFAFgBQAJgEATgBIArAAQAXABASAGIAUAIQANAFAJACQAIACAAADQAqAEAogQIAZgLQAPgGALgCIAFgCQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIBPADIAsAPQASAGAGAGQAFAEAJAMQAGAKADAHQADAIAAAQIgBBpIgJAFQABAbgNAxIgHAcQgJAjgLARIgJAOQgEAIABAHIhHAwQhNAXhNAAQgoAAgpgGgAi4iaIgTARQgJAJgBAEQgDAGAAAMIAAApQAAAVACAKQABAHAEALIAGAQQALAggEAQIALAFQgFAIAHANQAIAOAAAFIgBAKQAAAFABAEQABAGAIAGIAUAPQAXAQAQAEQAKAEACAEQBKAMAngEQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQACgCAEgBQAqgCAbgMQATgJAQgPIATgGQAAgDADgDIAHgEQAGgEAIgSQAHgQAJgBQAAgMAHgXIALgnQAJgfABgMIACgRQABgLADgHIAGgQQACgLgJgSQgMgZgMgSQgPABgMgKIg7ACQgHALgMgBIgLAPIifgDQgBgEgFgCQgEgCgFABQgOAAgCgIQgHABgNgFQgOgFgGAAQgPAAgUATgAgbCZQgfgBgRgIQgUgJgVgbQgjgvgNg7QgMg6ANg5QADgRAHgHQALgOAWADQASACASANIAhAWQATALAQgBQAKgBALgFIAVgLQAdgQAigCQAhgDAgAKQAeAKANARQAJALACANQABAOgGALIgogLQgBA4gHAfQgKAwgaAdQguA1hhAAIgDAAgAiBg4QAAAJAGAQIAMAhQANAhALANQAMAOgCAHQAWAaAcAPIAqgPQAagJAQgJQAVgNAMgTQANgVgDgVIALgEQgDgIADgJQACgJAHgFQgDgHABgMIABgUQgBgLgJgHQgJgIgIAFQgfAdgrAGQgSACgbgCQgfgBgRgHIgUgMQgNgHgJgBQgNAMABARg");
	this.shape_6.setTransform(38.7219,9.6586);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AAaCZQhhgBgxgFQhRgHg+gWQgngPgWgRQgVgPgbgiQggglAIgYIgKgFIgBgOQgYgOAFg0QAFABASgBQAOgBAIAEQAEACANALQAKAKAIgBQgDAEAEAEQADAEAGACIBZAeQAeALAUADQARADAjAAQCNACBKgIQB3gMBXgnQAbgMAPgMIAQgQQAKgKAHgFQAQgMAVgEQAUgDAUAGIAAAqIgJAGQgMAVAAAXIgJAFQgOAygdAbIgkAfIgfAbQgTAQgOAJQgsAdhCAKQgkAFg+AAIgVAAgAlBgEQASAcAdAUQAdAUAhAIIAVAMQBaATBZACQBsACBMgaQAYgKAagTIAZgTIBLg8QACgCgCgDQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIAAAIIgeAGQgaALgZALQhdARhlAGIhdAEIgzAAIiFgLQACgGgMgBQgbgDgXgNg");
	this.shape_7.setTransform(39.2746,0.9177);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},1).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[]},1).to({state:[{t:this.shape_5}]},1).to({state:[]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9.9,-14.7,105.5,53.099999999999994);


// stage content:
(lib.muñecoanimacion2112 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {Neutral:4,"Neutral":34,D:38,"Neutral":40,Oh:54,"Oh":56,Uh:57,S:60,Woo:63,"Oh":67,M:68,"Oh":71,"Woo":74,"M":77,"Woo":80,"S":84,Ee:86,"Oh":89,"Neutral":90,"Woo":91,"M":94,"Oh":97,"M":99,"Woo":102,"M":105,"Woo":108,"Neutral":110};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [34,110,111,119];
	// timeline functions:
	this.frame_34 = function() {
		playSound("CentroInformaticoCosladaonlineaudioconvertercom");
	}
	this.frame_110 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
		
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_4.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_3.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_3()
		{
			this.gotoAndPlay(112);
		}
	}
	this.frame_111 = function() {
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_5.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_5.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_5()
		{
			this.gotoAndPlay(1);
		}
	}
	this.frame_119 = function() {
		/* Hacer clic para ir al fotograma y reproducir
		Al hacer clic en la instancia del símbolo especificado, la cabeza lectora se mueve hasta el fotograma especificado en la línea de tiempo y prosigue la reproducción desde dicho fotograma.
		Se puede utilizar en la línea de tiempo principal o en líneas de tiempo de clips de película.
		
		Instrucciones:
		1. Reemplace el número 5 del siguiente código por el número de fotograma hasta el que quiere que se mueva la cabeza lectora cuando se haga clic en la instancia del símbolo.
		2.Los números de fotograma en EaselJS empiezan con 0 en vez de 1
		*/
		
		this.button_6.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_6.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_6()
		{
			this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(34).call(this.frame_34).wait(76).call(this.frame_110).wait(1).call(this.frame_111).wait(8).call(this.frame_119).wait(1));

	// ojos
	this.instance = new lib.ojos("synched",0);
	this.instance.setTransform(310.2,194.05);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(34).to({_off:false},0).to({_off:true},77).wait(9));

	// boca
	this.instance_1 = new lib.boca("single",11);
	this.instance_1.setTransform(329.2,301.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(34).to({_off:false},0).wait(4).to({startPosition:11},0).wait(2).to({startPosition:11},0).wait(14).to({startPosition:6},0).wait(2).to({startPosition:6},0).wait(1).to({startPosition:8},0).wait(3).to({startPosition:5},0).wait(3).to({startPosition:10},0).wait(4).to({startPosition:6},0).wait(1).to({startPosition:4},0).wait(3).to({startPosition:6},0).wait(3).to({startPosition:10},0).wait(3).to({startPosition:4},0).wait(3).to({startPosition:10},0).wait(4).to({startPosition:5},0).wait(2).to({startPosition:1},0).wait(3).to({startPosition:6},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:10},0).wait(3).to({startPosition:4},0).wait(3).to({startPosition:6},0).wait(2).to({startPosition:4},0).wait(3).to({startPosition:10},0).wait(3).to({startPosition:4},0).wait(3).to({startPosition:10},0).wait(2).to({startPosition:0},0).to({_off:true},1).wait(9));

	// flecha_final_
	this.button_6 = new lib.flechafinal();
	this.button_6.name = "button_6";
	this.button_6.setTransform(692.65,186.35,1,1,0,0,0,56.4,40.8);
	this.button_6._off = true;
	new cjs.ButtonHelper(this.button_6, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.button_6).wait(119).to({_off:false},0).wait(1));

	// narizinfo
	this.instance_2 = new lib.narizinfo();
	this.instance_2.setTransform(363.5,286.55,1,1,0,0,0,20.5,11.5);
	this.instance_2._off = true;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 2, false, new lib.narizinfo(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(111).to({_off:false},0).wait(9));

	// orejainfo
	this.instance_3 = new lib.orejainfo();
	this.instance_3.setTransform(464.95,258.85,1,1,0,0,0,20.2,34.1);
	new cjs.ButtonHelper(this.instance_3, 0, 1, 2, false, new lib.orejainfo(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AgFAZQADgxACAAQADAAADAv");
	this.shape.setTransform(463.05,222.5125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAAgYQADAAADAvIgLACQADgxACAAg");
	this.shape_1.setTransform(463.05,222.5125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance_3}]},111).wait(9));

	// ojoinfografia
	this.instance_4 = new lib.ojoinfografia();
	this.instance_4.setTransform(392.5,245.05,1,1,0,0,0,21.5,30);
	this.instance_4._off = true;
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2, false, new lib.ojoinfografia(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(111).to({_off:false},0).wait(9));

	// cara_infografia_
	this.instance_5 = new lib.ojos("synched",0);
	this.instance_5.setTransform(307.35,192.55);

	this.instance_6 = new lib.boca("single",4);
	this.instance_6.setTransform(322.6,314.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgYAYIAAgvIAxADIAAAsg");
	this.shape_2.setTransform(-215.95,280.925);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.instance_6},{t:this.instance_5}]},111).wait(9));

	// cara
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AiEaFQAEgEAJgCIAOgGQAMgGADABIgLAHIgLAIQgGADgIAAIgGgBgAAUZZIAOgEIAHgCIgXATQACgGAAgHgAodY/QgCgEABgGQAOAPATAQIgggVgAHLYHIAAAJIgCABIACgKgACiXoQghABgggEIAAAAQiagLiBgkQh3gig/g3IgagaIgagZQgYgXgrggIhEg0Qg4gtg3hAQgrgzgzhJQg5hTgWg0QgTgtgNg7QgFgagCgXIgGAAIg7gBQgPAAgGgDQgPgGgOgdIgehAIgRgoQgMglgBgwQgBgfgJgMQgDgFgIgFIgLgJQgPgOAGgMIgKgGIgWg+QgQgsgIgaQgLgogDghQgEhDAag9QAMgZAOgIIgFgZIgJgIQgHgHgSgNIhthRQghgYgUgGQgGgCgugIQgfgFgPgOQgBgUADgUIgCAAIAAgqIASgEIACgCIADgBQgBgQADgMQAagGAvAOIgCgDQgLgYgggSIg6gbQgMgGgLgIIgDAAIhMgCQgtgBgJgBQgggEgMgPQgLgPADgeQAEglgDgMIAegIIAAgYQAWADA1AAIA/gBQBCgTBIAHQBeAIBMAxQgMgygvgxQgSgShJg+Qh7hpAPhgQBpgLBdAzIAGADQAmgBAfALQAqAPAoAlQAVATAcAjQAOADAMACQAQACAGgHQAJgKgLgWQgIgSgYhBQgTgzgSgcQgXgkglgZQgkgZgqgJIgtgIQgbgFgQgJQgVgMgIgYQgIgYAOgRQBvglCIA0QA0AUA8AkQAlAWBFAvQgEgtgogqQgWgXg6grQhxhXAShQQCPgECLArQCLArB0BUQgKghgdgkIg0g+QhEhRANhBQA9gIBBAWQAMADAMADQArANAgAbIABgCIAVgBQANgBAIADQAIADAIAIIAMAPQApA0A7AbQgFgiAHgtQADgQAOg+QAIglAJgzQAHgtAAgbIgCgZIgBgjIgBggQAIACAZgBQAVgBALAGQAHAEAMAPIAGAHIAfAjQAaAaALAPQAUAaATAkQAJAUAUAvQAag7ArgxQAGgRAJgQQAGABAGgBIADgGQAEgJABgOIABgZIABgKQAEgbAOgtIBBACQAAAQAKASIATAeIADAGQALATAJAWIAEABIACARQAJAaAKAqQATBPAGA6QADAaAAAYQAFgOALgWIBRiaQAjhCAkg6IASgdIBCACIAeEgIAEAfQAEARAHALQAOgIAlgQQAggOARgLQAOgIAagUQAagTANgJIAIgEIAegXQCShoCqgKQALARgBAXQgBAUgKAUQgJAQgPARQgKALgUATIgmAkIgIALIinDlQA3gIAagFQAsgKAhgOIBHggQAqgOAeAMQAPAkgaAqQgJAOgQASIgbAfQglAsgcBCQgXA2gKA6QAMgIALgSQAYgkAFgFQAOgOAbgLIASgHIAZgTQAUgQAlglQAkglAUgRQA6guBKgQQBKgRBIAQIAAAMIAtABIAAAFIAUAFIAAAFIAUAFIAAArIgoAFIAAAFIgsAAIAAALQhDAWg7AjQgBAHgCAFQgGANgUASQgoAjglAnQgKAQgQAWIgcAlQgaAlgTAnQA6gBBEACIACBfQguAVg4AwQg4AwgxA8QgbAhgLALQgKAhgMAsIgKAkQAHAOAGAOIgVAAQgGAXABAMIAEAUIADATQABAOgHAeQgLAqgDArQgBATABAVIAJgBQAhABANATIAAABQAFAJABAOIgBAZQAAAQAFAdQAGAfAAAOQABAYgHAdQgEARgMAiIghBfQgLAggCANQgDAPAAAUIAAAkQACBWgOBTIgFAEIgEAPQgFAUgCAXQgEABgDADQgDAEABAEQgqAAgzgBIgHAOIgKAUQgUApgdA0QhAB2gYBAIjMD3Qg4BCgeAaQhOBFhoAiQgxAQgvAFIAAACIgZAAgAs/JGQAGAhgHAfQACAJABANQAHBMAvBTQAgA3BDBWQA6BKAnAqQA5A8A4AnIAvAfQAdATARAOQAMALATAUIAgAfQBUBNCZAfQAuAJBTALIArAFQBsgDBhguQAegOAVgQIATgRQALgLAIgFIAdgUQAPgNABgPQAPgIAQgQQAKgKARgVIBuiIIAogxIAxg4QAOgmASgkQAUgrAagoIAlg5IAJgOIASgcIAQgcQgEgMgBgOIACgkQACgWgDgNQAHACAXgBQATgBAIAHQAEAEADAGQAJgBAJgEQATgIAMgOQAEgfADgfIAAACIhBgDIAAgqIAZACQgBAGAGAEQAGAEAFgEQgFhDAKhdQAFglAGgkQAIgrAKgVIgqgGQgFgFAGgIQAFgGAIgDQALgDAEgDQAIgEABgHIAiACQAFAlgLAnIgJAaQgDAMgEAYIgHApQgIArgCAXQgDAlAFAdIABAEIABg2QAAgxAFgVIAQguIAPgsQASg2AEgeQAIgwgMglQgIABgKAFIgQAKQgRAKgUADIgBAFQgCANgEAIQgEAHgJAJIgOAOQgSATAEARIgtgDIAAiOIALgFQgCgLAAgMQAAgQADgSIAGgZIAJgfIAHgZIAEgTQAFgVgDgnIgUgFIAAhSQAAgxgQgcQgGgLgPgPIgOgQQABAKgBAIIgIAXQgFAOACAJIgeAHIAAAPIgfgCQgLgrgMgSQgIgMgRgQIgbgaIgLgQQgIABgJAEQgMAGgGAKIADAEQAMAOgCAdIgDAXQAAANACAJIgogCQgBgJgJgBIAAgBIgUACQghAFgLgOQgHgKAAgWIABhuQgrABgoAQQgZALgVAOQghA1gXBDIgDAAQgGAfAEATIgKAFIg8AAIAAgCQgLAAgGgMQgGgKAAgMIAAgEIABgKIABgFIgMAAQgKhVAkhNQgPgBgPABIgbAlQg0BIggAjQgNANgGAKIgDAGIgCAEQgDALgFACQgDADgHgBIgCABIgUAYIhoAAQAAgGgDgIIgFgLIgOgPIgJgKIgFgFIgCgDQgKgEgFgGQgFgGgDgKQgyg4g6gxQgZgXgVgKIgCANIgPBxQgTADgKgDQgHgDgEgGQgEgHACgHQgNgDgKgPIgQgcQgGgMgNgSIgMgSIgfALIgOBpQATAVAFAaIACAKIAAAOQgdACgQgBQgZgDgQgKIgDgCIgMgKIgDgCIgSgPQgSgMgdgDIg0gEQgJAAgGgFQgHgFADgGIgBAAIgNALQgYASgbAJQgkAYggAYIgKAUQgMAWgHALIgSAaQgJAMgFAJIgBAmQgDAwgSArIgLAcQgEAOgCAWQgIBIgBAbIgCA0IAAAHQAEARgDAeIgKAFIAAAdQgVAFgNgDQgFgCgFgDIAAABQgUAFgVgPQgMgIgSgXQgGALALAYQAhBAAHBIIAJAFQADAnAeAZIANgBIAAgPIAhACIgIArIhAgDQgQgMgMggQgOgngKgmIgJgkQgFgVgIgOIgIgPQgFgJgCgGQgDgNABgWQABgagBgJQASgBAKABQAPABALAFIADACIgGgZIgGAAQgEgVgKgVIgGgLIAAgCIgGgJIgMgTIgxgDQgHALgNgBQgDBEAGAhQAEAUAEAJQAHASALAFQAAAJAKASQANAXAJAKIAOAQQAGAIAFANQAIASACAKQACAKgBAPIAAAZQACAVAJAVIAJAFIAAAPIAKAFQgBALAIAUIAXA4QAHADABAIIBkACQAAgDADgDQADgDAEgBIABgUgAOkKAQADADACAFIANgFIgGgDIgQgEIAEAEgAwRAEIAlABIAAgBIglgDIAAADgAt+roIADgBIgEgFIABAGgAi0yCIADAAIgCghIgBAhgAiF2zIABAAIAAgEgAtnP3IAJADIAIAEIADAIQgLgGgJgJg");
	this.shape_3.setTransform(358.3179,217.8205);
	this.shape_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(34).to({_off:false},0).wait(86));

	// flecha
	this.button_4 = new lib.Símbolo1();
	this.button_4.name = "button_4";
	this.button_4.setTransform(696,199.3,1,1,0,0,0,68,54.6);
	this.button_4._off = true;
	new cjs.ButtonHelper(this.button_4, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.button_4).wait(110).to({_off:false},0).to({_off:true},1).wait(9));

	// muñeco
	this.instance_7 = new lib.muñeco("synched",0);
	this.instance_7.setTransform(24.75,149.05);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:594.4,y:155.25,startPosition:15},32).to({regX:47.9,regY:164.2,x:427.65,y:313.25,startPosition:16},1).to({_off:true},1).wait(86));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(181.6,350.9,598.3,149);
// library properties:
lib.properties = {
	id: 'BCD0A4C00B15D542B7E7477290399BAF',
	width: 800,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/muñeco animacion_atlas_1.png?1671625117438", id:"muñeco animacion_atlas_1"},
		{src:"sounds/CentroInformaticoCosladaonlineaudioconvertercom.mp3?1671625117486", id:"CentroInformaticoCosladaonlineaudioconvertercom"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['BCD0A4C00B15D542B7E7477290399BAF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;